package application.Mohamed;

import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.ResourceBundle;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.text.Text;
import tn.esprit.macdoloan.entity.Installment;
import tn.esprit.macdoloan.service.interf.ILoanServiceRemote;
import javafx.scene.layout.HBox;

import javafx.scene.control.Label;

import javafx.scene.layout.AnchorPane;

import javafx.scene.input.MouseEvent;

import javafx.scene.layout.BorderPane;

import javafx.scene.layout.VBox;

public class instalmentController implements Initializable {
	@FXML
	private BorderPane border;
	@FXML
	private AnchorPane Post;
	@FXML
	private VBox vbox;

	@FXML
	private Label lab_id;

	@FXML
	private Label lab_prix;

	@FXML
	private Label lab_date;
	@FXML
	private Text PostTf;

	// Event Listener on AnchorPane[#Post].onMouseClicked
	@FXML
	public void OpenPost(MouseEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		Installment t = new Installment();

		String jndiName = "macdoloan-ear/macdoloan-ejb/LoanServiceImpl!tn.esprit.macdoloan.service.interf.ILoanServiceRemote";
		Context context;
		try {
			context = new InitialContext();
			ILoanServiceRemote proxy = (ILoanServiceRemote) context.lookup(jndiName);
			int f = adminloanfController.id_loan;
			List<Installment> inst = proxy.findAllinstallementByloanId(f);

			for (Installment i : inst) {
				lab_id.setText(f + "");
				// lab_prix = new Label(i.getPrix()+"");
				lab_prix.setText(i.getPrix() + "");
				SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
				String dates = formatter.format(i.getRefunddatenddate());
				lab_date.setText(dates);

				// lab_date.setText(dates);
				/*HBox h = new HBox();
				HBox h1 = new HBox();
				HBox h2 = new HBox();

				h.setMaxSize(1000, 1000);
				h.getChildren().add(lab_id);
				h1.getChildren().add(lab_prix);
				h2.getChildren().add(lab_date);
				vbox.getChildren().add(h);
				vbox.getChildren().add(h1);
				vbox.getChildren().add(h2);*/

			}

		} catch (NamingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

}
